---
- name: Instalar Plex Media Server en Ubuntu 22.04
  hosts: my_servers
  become: yes

  tasks:
    - name: Actualizar lista de paquetes
      apt:
        update_cache: yes

    - name: Instalar paquetes necesarios
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg2
        - software-properties-common

    - name: Agregar la clave GPG de Plex
      apt_key:
        url: https://downloads.plex.tv/plex-keys/PlexSign.key

    - name: Agregar el repositorio de Plex al sistema
      apt_repository:
        repo: deb https://downloads.plex.tv/repo/deb public main
        state: present

    - name: Actualizar lista de paquetes después de agregar el repositorio
      apt:
        update_cache: yes

    - name: Instalar Plex Media Server
      apt:
        name: plexmediaserver
        state: present

    - name: Habilitar e iniciar el servicio Plex Media Server
      systemd:
        name: plexmediaserver
        state: started
        enabled: yes
